### ISSUE TITLE
ASS1_Những file được phép sửa

### ISSUE THREAD

**Issue by thanhlongdo** [saitamandd/PF162-Assignment#1]
Dear Thầy!

Em có vài thắc mắc mong thầy giải đáp : 
1. những file được sửa theo em hiểu đó là linearRegression.h , linearRegression.cpp , main.cpp . Lúc nộp cũng chỉ nộp những file này.
  Còn file commonlib.cpp thì hiện thực nhưng ko nộp.
2.  project em viết trên visual studio rồi đem những file yêu cầu rồi submit. Ngoài ra em có cần làm thêm gì nữa không? Vì em thấy trong project của thầy có nhiều file lạ như makefile,...

Best regard!
TLdo

**Comment by saitamandd** [comment]
1. Lúc nộp bạn chỉ nộp linearRegression.h, linearRegression.cpp nén vào file mã nguồn để đưa lên hệ thống. File commonLib.cpp hiện thực để các bạn tự test logic chương trình nhưng không nộp.
2. Các bạn muốn viết trên môi trường nào không quan trọng, chỉ cần tuân thủ đúng quy tắc của ngôn ngữ. Code submit sẽ được biên dịch trên môi trường linux dùng trình biên dịch chuẩn với chuẩn C++11. Các file kèm trong project là các file cấu hình cho hệ thống build, tôi đã có lần giói thiệu trên lớp.
